baseURL = "https://zjsxsjc1001.xyz"
title = "偽物"
themesDir = "./themes"
theme = "m10c"
paginate = 5

[permalinks]
  posts = "/:year/:month/:title/"

#render html tags in markdown
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  avatar = "avatar.jpg"
  author = "Shane Shi"
  description = "Ideas are bulletproof. - V for Vendetta"
  [[params.social]]
    name = "github"
    url = "https://github.com/sjc7217"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/zjsxsjc"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
